mysql:
  image: mysql
  ports:
    - "3307:3306"
  expose:
    - "3306"
  environment:
    - MYSQL_USER=root
    - MYSQL_PASSWORD=secret
    - MYSQL_DATABASE=db_example
    - MYSQL_ROOT_PASSWORD=root
  volumes:
    - "./conf.d:/etc/mysql/conf.d:ro"